apiVersion: v1
kind: Pod
metadata:
  name: db-client 
spec:
  containers:
  - name: db-client
    image: nginx:1.21
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-credentials 
          key: username
    - name: DB_PASSWORD 
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password 
