apiVersion: v1
data:
  another-param: another-value
  extra-param: extra-value
  my-config.txt: |-
    # This is a sample config file that I might use to configure an application
    parameter1 = value1
    parameter2 = value2
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-10T22:55:49Z"
  name: my-config
  namespace: default
  resourceVersion: "188655"
  uid: af6151f9-419a-4a89-9e74-d622b1f541e1
